[manager]
prepend_keymap= [
    { on  = ["g", "d", "d"], run = 'cd ~/Dirs/Downloads', desc = 'Go to Downloads' },
    { on  = ["g", "d", "o"], run = 'cd ~/Dirs/Documents', desc = 'Go to Documents' },
    { on  = ["g", "d", "D"], run = 'cd /mnt/D', desc = 'Go to D' },
    { on  = "y", run = [ "yank", "plugin wl-clipboard" ] },
    { on  = "<C-n>", run = ''' shell 'dragon-drop -x -i -A -T "$@"' --confirm ''', desc = 'Start drag-and-drop files' },
    { on   = [ "f", "j" ], run  = "plugin first-non-directory", desc = "Jumps to the first file" }
]
append_keymap= [
    { on  = ["g", "p"], run = 'cd ~/Dirs/Pictures', desc = 'Go to Pictures' },
    { on  = ["g", "v"], run = 'cd ~/Dirs/Videos', desc = 'Go to Videos' },
    { on  = ["g", "s"], run = 'cd /mnt/D/sagayda', desc = 'Go to my folder' },
    { on  = ["g", "k"], run = 'cd /mnt/D/sagayda/Si Pee Eye', desc = 'Go to my KPI folder' },
    { on  = ["g", "r"], run = 'cd "/mnt/D/sagayda/visual cock/repos"', desc = 'Go to rep' }
]
