[[manager.prepend_keymap]]
on  = ["g", "d", "d"]
run = 'cd /mnt/D/downloads'
desc = 'Go to Downloads'

[[manager.prepend_keymap]]
on  = ["g", "d", "o"]
run = 'cd /mnt/D/documents'
desc = 'Go to Documents'

[[manager.prepend_keymap]]
on  = ["g", "d", "D"]
run = 'cd /mnt/D'
desc = 'Go to D'

[[manager.append_keymap]]
on  = ["g", "p"]
run = 'cd /mnt/D/pictures'
desc = 'Go to Pictures'

[[manager.append_keymap]]
on  = ["g", "v"]
run = 'cd /mnt/D/videos'
desc = 'Go to Videos'

[[manager.append_keymap]]
on  = ["g", "s"]
run = 'cd /mnt/D/sagayda'
desc = 'Go to my folder'

[[manager.append_keymap]]
on  = ["g", "k"]
run = 'cd /mnt/D/sagayda/Si Pee Eye'
desc = 'Go to my KPI folder'

[[manager.append_keymap]]
on  = ["g", "r"]
run = 'cd "/mnt/D/sagayda/visual cock/repos"'
desc = 'Go to rep'

[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''', "yank" ]

[[manager.prepend_keymap]]
on  = "<C-n>"
run = '''
	shell 'dragon-drop -x -i -A -T "$@"' --confirm
'''
