[manager]
linemode = "size_and_mtime"
sort_by = "mtime"
sort_reverse = true

[opener]
proton = [
    { run = 'portproton "$@"', orphan = true }
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open" },
]

extract = [
]

[open]
prepend_rules = [
    { mime = "application/vnd.microsoft.portable-executable", use = "proton" },
    { mime = "application/microsoft.portable-executable", use = "proton" }
]
